### ISSUE TITLE
코드 문제

### ISSUE THREAD

**Issue by tongchangD** [HeaseoChung/BSRGAN-PyTorch#1]
당신의 코드가 참조하는 논문이 bsrgan 인가?

**Comment by HeaseoChung** [comment]
Yes :)

**Comment by tongchangD** [comment]
어떻게 코드를 테스트하는지, 테스트가 잘못 신고되었는지, 모형 파일에 문제가 있는지 알아냈다.How to test the code, I found that the test error, whether there is a problem with the model file.发自我的华为手机-------- 原始邮件 --------发件人： HeaseoChung ***@***.***>日期： 2021年8月4日周三 上午10:58收件人： HeaseoChung/BSRGAN-PyTorch ***@***.***>抄送： tongchangD ***@***.***>, Author ***@***.***>主    题： Re: [HeaseoChung/BSRGAN-PyTorch] 코드 문제 (#1)
Yes :)

**Comment by tongchangD** [comment]
good work
