### ISSUE TITLE
논문에서 데이터 처리는 어디에 있습니까?

### ISSUE THREAD

**Issue by tongchangD** [HeaseoChung/BSRGAN-PyTorch#2]
죄송합니다. 한국어를 모릅니다

논문에서 데이터 처리는 어디에 있습니까?

**Comment by tongchangD** [comment]
I'm sorry. I don't know Korean.
Can I communicate in English
Where is the data processing in the code?

**Comment by HeaseoChung** [comment]
> I'm sorry. I don't know Korean.
> 
> Can I communicate in English
> 
> Where is the data processing in the code?

The random shuffle data processing is included jn the degradation folder.

**Comment by tongchangD** [comment]
What‘s the original data file format look like.
train data and vaild data
Does it only contain HR image ？

**Comment by HeaseoChung** [comment]
> What‘s the original data file format look like.
> 
> train data and vaild data
> 
> Does it only contain HR image ？

All you need is HR data. The dataset.py automatically degrade HR data to make LR data for you

**Comment by tongchangD** [comment]
python train.py --train-file ./dataset/train/ --eval-file ./dataset/valid --outputs-dir ./output --scale 4 --pretrained-net ./pre-trained/BSRNet.pth
and my train-file File structure is 
./dataset/train/
├── 1.png
├── 2.png
├── 3.png
├── 4.png
└── 5.png

./dataset/valid/
├── 1.png
├── 2.png
├── 3.png
├── 4.png
└── 5.png

This is right or wrong？

**Comment by tongchangD** [comment]
RuntimeError: You need pre-trained BSRGAN.pth or generator & discriminator


Can you provide these two models

**Comment by HeaseoChung** [comment]
> python train.py --train-file ./dataset/train/ --eval-file ./dataset/valid --outputs-dir ./output --scale 4 --pretrained-net ./pre-trained/BSRNet.pth
> 
> and my train-file File structure is 
> 
> ./dataset/train/
> 
> ├── 1.png
> 
> ├── 2.png
> 
> ├── 3.png
> 
> ├── 4.png
> 
> └── 5.png
> 
> 
> 
> ./dataset/valid/
> 
> ├── a.png
> 
> ├── b.png
> 
> ├── c.png
> 
> ├── d.png
> 
> └── e.png
> 
> 
> 
> This is right or wrong？

It is right format

**Comment by HeaseoChung** [comment]
> RuntimeError: You need pre-trained BSRGAN.pth or generator & discriminator
> 
> 
> 
> 
> 
> Can you provide these two models

python train.py --train-file ./dataset/train/ --eval-file ./dataset/valid --outputs-dir ./output --scale 4 --pretrained-net ./pre-trained/BSRNet.pth

You already have BSRNet in the pretrained folder

**Comment by HeaseoChung** [comment]
> > RuntimeError: You need pre-trained BSRGAN.pth or generator & discriminator
> > 
> > 
> > 
> > 
> > 
> > Can you provide these two models
> 
> python train.py --train-file ./dataset/train/ --eval-file ./dataset/valid --outputs-dir ./output --scale 4 --pretrained-net ./pre-trained/BSRNet.pth
> 
> You already have BSRNet in the pretrained folder 

As long as you have the pretrained BSRNet, you don't need generator and discriminator. These two models are needed when you want to resume your train.

**Comment by tongchangD** [comment]
I want to train my own data

**Comment by HeaseoChung** [comment]
> I want to train my own data

When you read BSRGAN paper, you need the BSRNET pretrained model to make BSRGAN

**Comment by tongchangD** [comment]
![image](https://user-images.githubusercontent.com/36293393/128169758-0247fb4a-9ef6-4484-871a-6921f4682dfb.png)
 
I thought these can be used as pre-training models

**Comment by HeaseoChung** [comment]
> ![image](https://user-images.githubusercontent.com/36293393/128169758-0247fb4a-9ef6-4484-871a-6921f4682dfb.png)
> 
>  
> 
> I thought these can be used as pre-training models

I guess you want to do fine-tunning. I am not sure it is going to work or not, but you can put one of your bsrgan as pretrained-net for fine-tunning.

**Comment by tongchangD** [comment]
好的，谢谢

**Comment by HeaseoChung** [comment]
> 好的，谢谢
> OK, thanks

응, 수고해
OK, Fighting

**Comment by tongchangD** [comment]
Traceback (most recent call last):
  File "/media/tcd/data/github/SR/BSRGAN-PyTorch/train.py", line 191, in <module>
    lr = lr.to(device)
RuntimeError: CUDA error: unspecified launch failure


This is a sad story

**Comment by HeaseoChung** [comment]
> Traceback (most recent call last):
> File "/media/tcd/data/github/SR/BSRGAN-PyTorch/train.py", line 191, in
> lr = lr.to(device)
> RuntimeError: CUDA error: unspecified launch failure
> 
> This is a sad story

Probably, it's out of cuda memory. In order to fix the problem decrease size of patch and batch size.

**Comment by timfu248** [comment]
### NotImplementedError

the version of tensorflow and pytorch？

Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.6/dist-packages/lpips/weights/v0.1/vgg.pth
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    for i, (lr, hr) in enumerate(train_dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
**_NotImplementedError: Caught NotImplementedError in DataLoader worker process 0._**
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/HOSTDIR/TextSR/BSRGAN-PyTorch-master/dataset.py", line 35, in __getitem__
    lr = self.lr_transforms(hr)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 313, in __call__
    return self.lambd(img)
  File "/workspace/HOSTDIR/TextSR/BSRGAN-PyTorch-master/dataset.py", line 10, in degradation
    image = Image.fromarray(degradation_pipeline(np.array(image)).astype(np.uint8))
  File "/workspace/HOSTDIR/TextSR/BSRGAN-PyTorch-master/degradation/degradation.py", line 143, in degradation_pipeline
    img = get_camera(img, degrade_dict)
  File "/workspace/HOSTDIR/TextSR/BSRGAN-PyTorch-master/degradation/degradation.py", line 223, in get_camera
    deg_img = np.array(deg_img).astype(np.uint8)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
_**NotImplementedError: Cannot convert a symbolic Tensor (saturate_cast:0) to a numpy array.**_
