### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by tongchangD** [HeaseoChung/BSRGAN-PyTorch#3]
It's me again

Can you provide the version information

likes requirements.txt

**Comment by timfu248** [comment]
When I set --batch-size 1, it still prompt _RuntimeError: CUDA out of memory._ My GPU is T4...

**Comment by HeaseoChung** [comment]
torch==1.8.1
torchvision==0.9.1
tensorflow==2.5.0

**Comment by tongchangD** [comment]
> When I set --batch-size 1, it still prompt _RuntimeError: CUDA out of memory._ My GPU is T4...

我这也是 我 gpu 是2070的,然后 batch-size 设置的是 1 然后 patch-size 设置的64 ,在数据 转cuda 时,依旧上面的报错,像这样
lr torch.Size([1, 3, 16, 16])
HR torch.Size([1, 3, 64, 64])
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=719 : unspecified launch failure
Traceback (most recent call last):
  File "/media/tcd/data/github/SR/BSRGAN-PyTorch/train.py", line 203, in <module>
    lr = lr.to(device)
RuntimeError: CUDA error: unspecified launch failure
我不知道啥问题,我怀疑是 安装包的版本问题,
安装 HeaseoChung 他提供的版本 依旧是这个错误
不知道你有没有训练过 ESRGAN 论文代码.

**Comment by HeaseoChung** [comment]
I trained it using A100 with 40GB

**Comment by HeaseoChung** [comment]
> I trained it using A100 with 40GB.
> 
> If you want to take less cuda memory consumption, you need to make LR images using degradation.py and then you need 
to modify dataset.py to let you have LR and HR image as pair and remove degradation pipeline in the dataset.py.

==== dataset.py ====
import os
import random
import torchvision.transforms as transforms
from PIL import Image
from utils import check_image_file

class Dataset(object):
    def __init__(self, label_dir, input_dir, image_size, scale):
        self.label_dir = [os.path.join(label_dir, x) for x in os.listdir(label_dir) if check_image_file(x)]
        self.input_dir = [os.path.join(input_dir, x) for x in os.listdir(input_dir) if check_image_file(x)]

        self.label_dir.sort()
        self.input_dir.sort()

        self.image_size = image_size
        self.to_Tensor = transforms.ToTensor()
        self.resize = transforms.Resize((image_size // scale, image_size // scale), interpolation=Image.BICUBIC)
        self.rotates = [0, 90, 180, 270]

    """ 데이터 어그멘테이션 """
    def data_augmentation(self, hr, lr):
        """ 이미지 가로 세로 값 """
        width, height = hr.size
        """ 랜덤 이미지 포지션 """
        x = random.randint(0, width - self.image_size)
        y = random.randint(0, height - self.image_size)
        
        """ 크롭 이미지 """
        hr = hr.crop((x, y, x+self.image_size, y+self.image_size))
        lr = lr.crop((x, y, x+self.image_size, y+self.image_size))

        """ 리사이즈 이미지 """
        # hr = hr.resize((self.image_size, self.image_size), resample=Image.BICUBIC)
        # lr = lr.resize((self.image_size, self.image_size), resample=Image.BICUBIC)

        """ 이미지 회전 """
        deg = random.choice(self.rotates)
        hr = hr.rotate(deg)
        lr = lr.rotate(deg)
        """ 이미지 좌우반전 """
        flip_left_right = random.choice([True, False])
        if flip_left_right:
            hr = hr.transpose(method=Image.FLIP_LEFT_RIGHT)
            lr = lr.transpose(method=Image.FLIP_LEFT_RIGHT)
        """ 이미지 상하반전 """
        flip_up_down = random.choice([True, False])
        if flip_up_down:
            hr = hr.transpose(method=Image.FLIP_TOP_BOTTOM)
            lr = lr.transpose(method=Image.FLIP_TOP_BOTTOM)
        return hr, self.resize(lr)

    # lr & hr 이미지를 읽고 크롭하여 lr & hr 이미지를 반환하는 함수
    def __getitem__(self, idx):
        """ 데이터 이름 정보 프린트 """
        #print(f'hr : {self.label_dir[idx]}, lr : {self.input_dir[idx]}')
        hr = Image.open(self.label_dir[idx]).convert("RGB") # HR 이미지 생성
        lr = Image.open(self.input_dir[idx]).convert("RGB") # LR 이미지 생성
        """ 사이즈 프린트 """
        #print(f'hr size : {hr.size}, lr size : {lr.size}')
        hr, lr = self.data_augmentation(hr, lr) # 이미지 어그멘테이션 적용
        return self.to_Tensor(lr), self.to_Tensor(hr) # 데이터 셋 반환

    def __len__(self):
        return len(self.label_dir)

**Comment by HeaseoChung** [comment]
> > When I set --batch-size 1, it still prompt _RuntimeError: CUDA out of memory._ My GPU is T4...
> 
> 我这也是 我 gpu 是2070的,然后 batch-size 设置的是 1 然后 patch-size 设置的64 ,在数据 转cuda 时,依旧上面的报错,像这样
> lr torch.Size([1, 3, 16, 16])
> HR torch.Size([1, 3, 64, 64])
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=719 : unspecified launch failure
> Traceback (most recent call last):
> File "/media/tcd/data/github/SR/BSRGAN-PyTorch/train.py", line 203, in 
> lr = lr.to(device)
> RuntimeError: CUDA error: unspecified launch failure
> 我不知道啥问题,我怀疑是 安装包的版本问题,
> 安装 HeaseoChung 他提供的版本 依旧是这个错误
> 不知道你有没有训练过 ESRGAN 论文代码.

I change ISP algorithms not to use Tensorflow to take less cuda memory.

**Comment by tongchangD** [comment]
> I changed ISP algorithms not to use Tensorflow to take less cuda memory.

thanks
